name: deploy-to-website
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        uses: actions/checkout@v2
        with:
          node-version: "16"
      - name: Installation
        run: npm install

      - name: Run Build
        run: npm run build
        run: echo "Successfully built website"

      - name: Run deploy
        run: npm run deploy
        run: echo "Successfully deployed website"
